app = "eternal-garden-a73176df-65af-4df0-baca-8f823836ad9e"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "stop"
auto_start_machines = true
min_machines_running = 0

[env]
NODE_ENV = 'production'

[[vm]]
memory = "512mb"
cpu_kind = "shared"
cpus = 1
